# Generated by Django 2.2.13 on 2020-10-21 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Mcq', '0002_mark'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Mark',
            new_name='Marks',
        ),
    ]
